name: CI for Frontend

on:
  push:
    paths:
      - frontend/src/**
    branches:
      - master

defaults:
  run:
    working-directory: frontend

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.4.0
      - name: Cache node_modules
        uses: actions/cache@v2.0.0
        with:
          path: ~/.npm
          key: frontend-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: frontend-npm-
      - name: Install dependencies
        run: npm ci
      - name: Run ESlint
        run: npm run lint
      - name: Run Prettier
        run: npm run fmt
