openapi: 3.0.3
info:
  title: Jibacco Main API
  description: The first backend API handling frontend requests via nginx
  version: 0.0.1
  # ========== others ==========
  # contact: API 管理者の連絡先
  # license: ライセンスの情報
  # termsOfService: API の利用規約

servers:
  - url: http://localhost:3000
    description: local API server

tags:
  - name: users
    description: Access to Users

paths:
  /users:
    get:
      tags:
        - users
      summary: Returns an array of users
      description: Optional extended description in CommonMark or HTML
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
components:
security:
externalDocs: