openapi: 3.0.3
info:
  title: Jibacco Main API
  description: The first backend API handling frontend requests via nginx
  version: 0.0.1
  # ========== others ==========
  # contact: API 管理者の連絡先
  # license: ライセンスの情報
  # termsOfService: API の利用規約

servers:
  - url: http://localhost:3000/main-api/v1
    description: Development main API server

tags:
  - name: user
    description: Access to Users

paths:
  /users:
    get:
      tags:
        - user
      summary: Get all users
      description: Returns an array of User model
      responses:
        '200':
          $ref: '#/components/responses/success' 

components:
  responses:
    success:
      description: Success
      content:
        application/json:
          schema: 
            type: array
            items:
              $ref: '#/components/schemas/User'
          examples:
            users:
              $ref: '#/components/examples/Users'
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      required:
        - id
        - name

  examples:
    Users:
      value:
        - id: 1
          name: Haruhi Suzumiya
        - id: 2
          name: 涼宮ハルヒ

security:
externalDocs: