source "https://rubygems.org"
git_source(:github) {|repo| "https://github.com/#{repo}.git"}

ruby '2.7.1'

gem 'rails', '~> 6.0.3'
gem 'puma', '~> 4.3'
gem 'mysql2', '~> 0.5.3'
gem 'redis', '~> 4.2'
gem 'rack-cors'
gem 'bootsnap', require: false

group :development do
  gem 'listen'
  gem 'spring'
  gem 'spring-watcher-listen'
  gem 'rubocop', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false
end

group :test do
  gem 'capybara'
  gem 'selenium-webdriver'
  gem 'webdrivers'
  gem 'rspec-rails'
  gem 'factory_bot_rails'
end
