version: '3.8'

services:
  main_db:
    build:
      context: ../
      dockerfile: backend/main_db/docker/dev.dockerfile
    env_file: ../backend/main_db/env/dev.env
  
  cache_db:
    build:
      context: ../
      dockerfile: backend/cache_db/docker/dev.dockerfile
    env_file: ../backend/cache_db/env/dev.env
    sysctls:
      net.core.somaxconn: 1024

  main_api:
    build:
      context: ../
      dockerfile: backend/main_api/docker/dev.dockerfile
    command: ./cmd/start_server/dev.sh
    env_file: ../backend/main_api/env/dev.env

  proxy:
    build:
      context: ../
      dockerfile: proxy/docker/dev.dockerfile

  frontend:
    build:
      context: ../
      dockerfile: frontend/docker/dev.dockerfile
    command: npm run build:dev
    env_file: ../frontend/env/dev.env
