version: '3.8'

services:
  main_db:
    build:
      context: ../
      dockerfile: backend/docker/main_db/prod.dockerfile
    env_file: ../backend/env/main_db/prod.dev

  cache_db:
    build:
      context: ../
      dockerfile: backend/docker/cache_db/prod.dockerfile

  main_api:
    build:
      context: ../
      dockerfile: backend/docker/main_api/prod.dockerfile
    command: ./cmd/start_server/prod.sh
    env_file: ../backend/env/main_api/prod.env

  proxy:
    build:
      context: ../
      dockerfile: proxy/docker/prod.dockerfile

  frontend:
    build:
      context: ../
      dockerfile: frontend/docker/prod.dockerfile
    command: bash # npm run build:prod
    env_file: ../frontend/env/prod.env
    tty: true

