version: '3.8'

services:
  main_db:
    build:
      context: ../
      dockerfile: backend/main_db/docker/prod.dockerfile
    env_file: ../backend/main_db/env/prod.dev

  cache_db:
    build:
      context: ../
      dockerfile: backend/cache_db/docker/prod.dockerfile

  main_api:
    build:
      context: ../
      dockerfile: backend/main_api/docker/prod.dockerfile
    command: ./cmd/start_server/prod.sh
    env_file: ../backend/main_api/env/prod.env

  proxy:
    build:
      context: ../
      dockerfile: proxy/docker/prod.dockerfile

  frontend:
    build:
      context: ../
      dockerfile: frontend/docker/prod.dockerfile
    command: bash # npm run build:prod
    env_file: ../frontend/env/prod.env
    tty: true

