version: '3.8'

services:
  main_db:
    build:
      context: ../
      dockerfile: backend/main_db/docker/dev.dockerfile
    env_file: ../backend/main_db/env/dev.env
  
  cache_db:
    build:
      context: ../
      dockerfile: backend/cache_db/docker/dev.dockerfile
    env_file: ../backend/cache_db/env/dev.env
    sysctls:
      net.core.somaxconn: 1024

  main_api:
    build:
      context: ../
      dockerfile: backend/main_api/docker/dev.dockerfile
    command: ./cmd/start_server/dev.sh
    env_file: ../backend/main_api/env/dev.env

  proxy:
    build:
      context: ../
      dockerfile: proxy/docker/dev.dockerfile

  frontend:
    build:
      context: ../
      dockerfile: frontend/docker/dev.dockerfile
    command: npm run build:dev
    env_file: ../frontend/env/dev.env

  swagger:
    build:
      context: ../
      dockerfile: swagger/docker/dev.dockerfile
    command: >
      swagger-ui-watcher
      --no-open
      --host 0.0.0.0
      --port 8080
      /swagger/index.yml
    container_name: jbc_swagger_cont
    image: jbc_swagger_img
    ports:
      - 8080:8080
    volumes:
      - ../swagger:/swagger
