version: '3.8'

services:
  main_db:
    build:
      context: ../
      dockerfile: backend/docker/main_db/prod.dockerfile
    env_file: ../backend/env/main_db/prod.dev

  cache_db:
    build:
      context: ../
      dockerfile: backend/docker/cache_db/prod.dockerfile

  main_api:
    build:
      context: ../
      dockerfile: backend/docker/main_api/prod.dockerfile
    # シェル化する : シェルの作成ディレクトリをどうするか
    command: >
      bundle check || bundle install -j4
      rm -f ../backend/main_api/tmp/pids/server.pid
      bundle exec puma -C ../backend/main_api/config/puma.rb -e production
    env_file: ../backend/env/main_api/prod.env