version: "3.8"

services:
  main_db:
    container_name: jbc_main_db_cont
    image: jbc_main_db_img
    ports:
      - 3306:3306
    volumes:
      - main_db_vol:/var/lib/mysql
      - ../backend/log/main_db:/var/log

  cache_db:
    command: redis-server /usr/local/etc/redis/redis.conf
    container_name: jbc_cache_db_cont
    image: jbc_cache_db_img
    ports:
      - 6379:6379
    volumes:
      - cache_db_vol:/data
      - ../backend/log/cache_db:/var/log

  main_api:
    container_name: jbc_main_api_cont
    depends_on:
      - main_db
      - cache_db
    image: jbc_main_api_img
    ports:
      - 3000:3000
    volumes:
      - main_api_bundle_vol:/usr/local/bundle
      - ../backend/main_api:/main_api
      - ../backend/log/main_api:/var/log

  proxy:
    command: nginx -c nginx.conf -g 'daemon off;'
    container_name: jbc_proxy_cont
    depends_on:
      - main_api
      - frontend
    image: jbc_proxy_img
    ports:
      - 80:80
    volumes:
      - frontend_proxy_vol:/usr/share/nginx/html
      - ../proxy/log:/var/log/nginx

  frontend:
    container_name: jbc_frontend_cont
    image: jbc_frontend_img
    ports:
      - 8000:8000 # webpack
      - 6006:6006 # stroybook
    volumes:
      - frontend_node_mod_vol:/frontend/node_modules
      - frontend_proxy_vol:/frontend/public
      - ../frontend:/frontend

volumes:
  main_db_vol:
  cache_db_vol:
  main_api_bundle_vol:
  frontend_node_mod_vol:
  frontend_proxy_vol:
