version: '3.8'

services:
  main_db:
    build:
      context: ../
      dockerfile: backend/docker/main_db/dev.dockerfile
    env_file: ../backend/env/main_db/dev.env
  
  cache_db:
    build:
      context: ../
      dockerfile: backend/docker/cache_db/dev.dockerfile
    env_file: ../backend/env/cache_db/dev.env
    sysctls:
      net.core.somaxconn: 1024

  main_api:
    build:
      context: ../
      dockerfile: backend/docker/main_api/dev.dockerfile
    command: ./cmd/start_server/dev.sh
    env_file: ../backend/env/main_api/dev.env

  proxy:
    build:
      context: ../
      dockerfile: proxy/docker/dev.dockerfile

  frontend:
    build:
      context: ../
      dockerfile: frontend/docker/dev.dockerfile
    command: npm run build:dev
    env_file: ../frontend/env/dev.env
    tty: true
